In [17]:
import os

import keras
#from keras.models import model_from_json 

import tensorflow as tf
from tensorflow import lite
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing import image
from shutil import copyfile
import matplotlib.pyplot as plt
import numpy as np

In [18]:
# 저장된 JSON 파일로 부터 모델 로드하기
json_file = open("model.json", "r") 
loaded_model_json = json_file.read() 
json_file.close() 
loaded_model = tf.keras.models.model_from_json(loaded_model_json)

# 로드한 모델에 Weight 로드하기
keras_file="flower.h5"
loaded_model.load_weights (keras_file)

# 로드한 모델 컴파일
loaded_model.compile(loss = "categorical_crossentropy", optimizer = RMSprop(lr=0.001), metrics = ['accuracy'])


# TEST
test_path = ["test/daisy_test.jpg","test/dandelion_test.jpg","test/rose_test.jpg","test/sunflower_test.jpg","test/tulip_test.jpg"]

for path in test_path : 
    
    img=image.load_img(path,target_size=(300,300))
    x=image.img_to_array(img)
    x=np.expand_dims(x, axis=0)
    images = np.vstack([x])

    ## 예측
    sonuc = loaded_model.predict(images, batch_size=10)
    print(sonuc[0])
    print(np.argmax(sonuc))
    a=np.argmax(sonuc)
    print(a)
    if a==0:
        print("it is a daisy")
    if a==1:
        print("it is a dandelion")
    if a==2:
        print("it is a rose")
    if a==3:
        print("it is a sunflower")
    if a==4:
        print("it is a tulip")

[1. 0. 0. 0. 0.]
0
0
it is a daisy
[1. 0. 0. 0. 0.]
0
0
it is a daisy
[0. 0. 0. 0. 1.]
4
4
it is a tulip
[0. 0. 0. 1. 0.]
3
3
it is a sunflower
[0. 0. 0. 0. 1.]
4
4
it is a tulip
